import { describe, expect, it } from 'vitest'

import type { CompanionClient, CompanionModel } from './companionClient'
import {
  chooseAgentModelSelection,
  finalizeAssistantTurn,
  resolveToolArguments,
} from './useAgentSession'

function model(
  id: string,
  efforts: readonly string[],
  defaultReasoningEffort = efforts[0] ?? 'medium',
): CompanionModel {
  return {
    id,
    model: id,
    displayName: id.toUpperCase(),
    description: '',
    supportedReasoningEfforts: efforts.map((reasoningEffort) => ({
      reasoningEffort,
      description: '',
    })),
    defaultReasoningEffort,
  }
}

describe('agent model selection', () => {
  it('offers only GPT-5.5 and GPT-5.6 and respects an allowed live default', () => {
    expect(
      chooseAgentModelSelection({
        available: true,
        connected: true,
        models: [
          model('gpt-5.4', ['medium']),
          model('gpt-5.5', ['low', 'medium', 'high']),
          model('gpt-5.6-terra', ['low', 'medium']),
        ],
        defaultModel: 'gpt-5.6-terra',
        defaultEffort: 'high',
      }),
    ).toMatchObject({
      modelId: 'gpt-5.6-terra',
      effort: 'medium',
      models: [{ id: 'gpt-5.5' }, { id: 'gpt-5.6-terra' }],
    })
  })

  it('defaults to Medium when available and otherwise uses the model default', () => {
    expect(
      chooseAgentModelSelection({
        available: true,
        connected: true,
        models: [model('gpt-5.5', ['low', 'medium', 'high'], 'high')],
        defaultModel: null,
        defaultEffort: 'low',
      }).effort,
    ).toBe('medium')

    expect(
      chooseAgentModelSelection({
        available: true,
        connected: true,
        models: [model('gpt-5.6-sol', ['high', 'xhigh'], 'xhigh')],
        defaultModel: null,
        defaultEffort: 'medium',
      }).effort,
    ).toBe('xhigh')
  })
})

describe('assistant turn finalization', () => {
  it('refuses to persist partial text when the stream ends without a terminal event', () => {
    expect(
      finalizeAssistantTurn({
        sawTerminalEvent: false,
        completedStatus: 'completed',
        cancelled: false,
        completedText: null,
        streamedText: 'A partial answer that must not be saved',
      }),
    ).toMatchObject({
      ok: false,
      message: expect.stringContaining('No partial reply was saved'),
    })
  })

  it('persists one finalized reply only for a completed terminal turn', () => {
    expect(
      finalizeAssistantTurn({
        sawTerminalEvent: true,
        completedStatus: 'completed',
        cancelled: false,
        completedText: ' Final answer. ',
        streamedText: 'Partial',
      }),
    ).toEqual({ ok: true, text: 'Final answer.' })

    expect(
      finalizeAssistantTurn({
        sawTerminalEvent: true,
        completedStatus: 'interrupted',
        cancelled: true,
        completedText: null,
        streamedText: 'Cancelled partial text',
      }),
    ).toEqual({ ok: true, text: null })
  })

  it('rejects a failed terminal turn without persisting partial text', () => {
    expect(
      finalizeAssistantTurn({
        sawTerminalEvent: true,
        completedStatus: 'failed',
        cancelled: false,
        completedText: null,
        streamedText: 'Partial reply',
      }),
    ).toEqual({
      ok: false,
      message:
        'The local AI turn ended with status failed. No partial reply was saved.',
    })
  })
})

describe('generated image handoff', () => {
  it('retrieves generated bytes out of band and supplies a Blob to the editor tool', async () => {
    const generatedBlob = new Blob([new Uint8Array([137, 80, 78, 71])], {
      type: 'image/png',
    })
    const getGeneratedImage = async () => generatedBlob
    const client = { getGeneratedImage } as unknown as CompanionClient

    const resolved = await resolveToolArguments(
      client,
      {
        type: 'tool-call',
        callId: 'call-1',
        name: 'scrollsplice.import_latest_generated_asset',
        arguments: {
          episodeId: 'episode-1',
          expectedRevision: 0,
          generationRef: 'opaque-generation-ref',
          metadata: { displayName: 'Generated panel', provider: 'OpenAI' },
        },
      },
      new AbortController().signal,
    )

    expect(resolved).toMatchObject({
      episodeId: 'episode-1',
      expectedRevision: 0,
      metadata: { displayName: 'Generated panel', provider: 'OpenAI' },
      source: generatedBlob,
    })
    expect(resolved).not.toHaveProperty('generationRef')
  })
})
